package studio

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

const (
	gitReadTimeout    = 3 * time.Second
	maxGitOutputBytes = 1 << 20
	gitWaitDelay      = 250 * time.Millisecond
)

// cappedCommandOutput keeps command output memory-bounded while continuing to
// drain the pipe. Returning len(p), nil after the cap is important: stopping
// the copy goroutine early can leave a verbose child blocked on a full pipe.
type cappedCommandOutput struct {
	data      []byte
	limit     int
	truncated bool
}

func (b *cappedCommandOutput) Write(p []byte) (int, error) {
	written := len(p)
	if b.limit <= 0 || len(b.data) >= b.limit {
		if written > 0 && b.limit > 0 {
			b.truncated = true
		}
		return written, nil
	}
	remaining := b.limit - len(b.data)
	if len(p) > remaining {
		b.truncated = true
		p = p[:remaining]
	}
	b.data = append(b.data, p...)
	return written, nil
}

func (b *cappedCommandOutput) String() string { return string(b.data) }

// GitFileChange is one entry from `git status --porcelain`.
//
//	Status is the two-letter porcelain code ("M ", " M", "??", "A ", etc.)
//	normalised to a human label: "modified", "added", "deleted", "untracked".
//	The frontend uses Status to colour the chip and Path as the click action.
type GitFileChange struct {
	Path   string `json:"path"`
	Status string `json:"status"`
}

// GitCommit is one entry from `git log --pretty=...`.
type GitCommit struct {
	Hash    string `json:"hash"`    // 7-char short hash
	Subject string `json:"subject"` // first line of the commit message
	Age     string `json:"age"`     // human-readable "3 hours ago", computed locally
	AgeMs   int64  `json:"ageMs"`   // raw age in millis for sort/format choices
}

// ProjectGitContext is what the frontend's smart welcome screen renders.
// All fields are best-effort: an empty Branch / nil ChangedFiles / nil
// RecentCommits all mean "git not available or this isn't a repo" — the
// frontend shrugs and shows the language-detection welcome instead.
type ProjectGitContext struct {
	Branch         string          `json:"branch,omitempty"`
	IsRepo         bool            `json:"isRepo"`
	ChangedFiles   []GitFileChange `json:"changedFiles,omitempty"`
	UntrackedFiles []GitFileChange `json:"untrackedFiles,omitempty"`
	RecentCommits  []GitCommit     `json:"recentCommits,omitempty"`
	// AheadBehind: "+3 -1" if the branch is 3 ahead and 1 behind upstream;
	// "" if there's no upstream or it can't be determined.
	AheadBehind string `json:"aheadBehind,omitempty"`
	// Insertions / Deletions: summed line counts of uncommitted tracked
	// changes vs HEAD (`git diff HEAD --numstat`). Untracked files are not
	// counted (they're not in the diff). Both 0 = clean tracked tree.
	Insertions int `json:"insertions,omitempty"`
	Deletions  int `json:"deletions,omitempty"`
}

// ProjectGitReview is a bounded, read-only snapshot of all tracked working
// tree changes versus HEAD. External diff drivers and textconv filters are
// disabled so opening the review cannot execute repository-provided helpers.
type ProjectGitReview struct {
	IsRepo          bool                `json:"isRepo"`
	Branch          string              `json:"branch,omitempty"`
	Files           []GitReviewFile     `json:"files,omitempty"`
	Insertions      int                 `json:"insertions,omitempty"`
	Deletions       int                 `json:"deletions,omitempty"`
	Diff            string              `json:"diff,omitempty"`
	Truncated       bool                `json:"truncated,omitempty"`
	Fingerprint     string              `json:"fingerprint,omitempty"`
	Findings        []CodeReviewFinding `json:"findings,omitempty"`
	ReviewCompleted bool                `json:"reviewCompleted,omitempty"`
}

// GitReviewFile is one bounded file patch in the visual change-review pane.
// PreviousPath is populated for renames. Patch is intentionally generated by
// Git with external diff/textconv disabled, or locally for an untracked file.
type GitReviewFile struct {
	Path         string `json:"path"`
	PreviousPath string `json:"previousPath,omitempty"`
	Status       string `json:"status"`
	Patch        string `json:"patch,omitempty"`
	Insertions   int    `json:"insertions,omitempty"`
	Deletions    int    `json:"deletions,omitempty"`
	Binary       bool   `json:"binary,omitempty"`
	Truncated    bool   `json:"truncated,omitempty"`
}

const (
	gitReviewMaxFiles         = 200
	gitReviewMaxFileBytes     = 256 << 10
	gitReviewMaxCombinedBytes = 1 << 20
)

// GetProjectGitReview returns a safe unified diff for explicit user review.
// Untracked paths remain available through GetProjectGitContext; Git has no
// baseline for their content, so the UI lists them separately instead of
// pretending they are part of this patch.
func (s *Studio) GetProjectGitReview(projectID string) (*ProjectGitReview, error) {
	s.mu.RLock()
	p, ok := s.projects[projectID]
	s.mu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("project not found: %s", projectID)
	}
	p.mu.RLock()
	dir := p.Directory
	p.mu.RUnlock()
	return gitReviewAt(dir)
}

// GetSessionGitReview reviews the checkout used by the selected conversation.
// It fails closed when persisted worktree metadata is unavailable or invalid,
// matching terminal, file-preview and agent tool routing.
func (s *Studio) GetSessionGitReview(projectID, sessionID string) (*ProjectGitReview, error) {
	p, session, err := s.projectSession(projectID, sessionID)
	if err != nil {
		return nil, err
	}
	dir, err := sessionWorkingDirectory(p, session)
	if err != nil {
		return nil, err
	}
	review, err := gitReviewAt(dir)
	if err != nil {
		return nil, err
	}
	s.attachCodeReviewFindings(projectID, sessionID, review)
	return review, nil
}

type gitReviewStatusEntry struct {
	path         string
	previousPath string
	status       string
}

func gitReviewAt(dir string) (*ProjectGitReview, error) {
	out := &ProjectGitReview{}
	if !runGitBool(dir, "rev-parse", "--is-inside-work-tree") {
		return out, nil
	}
	out.IsRepo = true
	out.Branch = runGit(dir, "rev-parse", "--abbrev-ref", "HEAD")

	statusRaw, statusTruncated, err := runBoundedGitReview(dir, maxGitOutputBytes,
		"status", "--porcelain=v1", "-z", "--untracked-files=all")
	if err != nil {
		return nil, fmt.Errorf("git status failed: %w", err)
	}
	entries := parseGitReviewStatus(statusRaw)
	if len(entries) > gitReviewMaxFiles {
		entries = entries[:gitReviewMaxFiles]
		out.Truncated = true
	}
	out.Truncated = out.Truncated || statusTruncated
	hasHead := runGit(dir, "rev-parse", "--verify", "HEAD") != ""
	combined := &bytes.Buffer{}
	fingerprint := sha256.New()
	_, _ = fingerprint.Write(statusRaw)

	for _, entry := range entries {
		file := GitReviewFile{
			Path:         entry.path,
			PreviousPath: entry.previousPath,
			Status:       entry.status,
		}
		remaining := gitReviewMaxCombinedBytes - combined.Len()
		if remaining <= 0 {
			file.Truncated = true
			out.Truncated = true
			out.Files = append(out.Files, file)
			continue
		}
		limit := gitReviewMaxFileBytes
		if remaining < limit {
			limit = remaining
		}

		var patch string
		var truncated bool
		if entry.status == "untracked" || (!hasHead && entry.status != "deleted") {
			patch, file.Binary, truncated = renderUntrackedGitPatch(dir, entry.path, limit)
		} else {
			args := []string{"diff", "--no-ext-diff", "--no-textconv", "--no-color", "--unified=3"}
			if hasHead {
				args = append(args, "HEAD")
			} else {
				args = append(args, "--cached")
			}
			args = append(args, "--", entry.path)
			if entry.previousPath != "" {
				args = append(args, entry.previousPath)
			}
			patchBytes, capped, patchErr := runBoundedGitReview(dir, limit, args...)
			if patchErr != nil {
				return nil, fmt.Errorf("git diff %q failed: %w", entry.path, patchErr)
			}
			patch = strings.TrimRight(string(patchBytes), "\n")
			truncated = capped
			file.Binary = strings.Contains(patch, "Binary files ") || strings.Contains(patch, "GIT binary patch")
		}
		if len(patch) > limit {
			patch = truncateGitReviewPatch(patch, limit)
			truncated = true
		}
		file.Patch = patch
		file.Truncated = truncated
		file.Insertions, file.Deletions = countReviewPatchLines(patch)
		out.Insertions += file.Insertions
		out.Deletions += file.Deletions
		out.Truncated = out.Truncated || truncated
		out.Files = append(out.Files, file)
		if patch != "" {
			if combined.Len() > 0 {
				combined.WriteString("\n")
			}
			combined.WriteString(patch)
			combined.WriteByte('\n')
			_, _ = fingerprint.Write([]byte(patch))
		}
	}
	out.Diff = strings.TrimRight(combined.String(), "\n")
	out.Fingerprint = hex.EncodeToString(fingerprint.Sum(nil))[:16]
	return out, nil
}

func parseGitReviewStatus(raw []byte) []gitReviewStatusEntry {
	fields := bytes.Split(raw, []byte{0})
	entries := make([]gitReviewStatusEntry, 0, len(fields))
	for index := 0; index < len(fields); index++ {
		field := fields[index]
		if len(field) < 4 {
			continue
		}
		code := string(field[:2])
		path := string(field[3:])
		if path == "" || !utf8.ValidString(path) {
			continue
		}
		entry := gitReviewStatusEntry{path: filepath.ToSlash(path), status: normalizeGitReviewStatus(code)}
		if strings.ContainsAny(code, "RC") && index+1 < len(fields) {
			index++
			previous := string(fields[index])
			if utf8.ValidString(previous) {
				entry.previousPath = filepath.ToSlash(previous)
			}
		}
		entries = append(entries, entry)
	}
	return entries
}

func normalizeGitReviewStatus(code string) string {
	switch {
	case code == "??":
		return "untracked"
	case strings.Contains(code, "R"):
		return "renamed"
	case strings.Contains(code, "C"):
		return "copied"
	case strings.Contains(code, "D"):
		return "deleted"
	case strings.Contains(code, "A"):
		return "added"
	case strings.Contains(code, "M"):
		return "modified"
	default:
		return "changed"
	}
}

func runBoundedGitReview(dir string, limit int, args ...string) ([]byte, bool, error) {
	ctx, cancel := context.WithTimeout(context.Background(), gitReadTimeout)
	defer cancel()
	full := []string{"-c", "core.hooksPath=/dev/null", "-c", "core.fsmonitor=false", "-C", dir}
	full = append(full, args...)
	cmd := exec.CommandContext(ctx, "git", full...)
	cmd.WaitDelay = gitWaitDelay
	output := &cappedCommandOutput{limit: limit}
	cmd.Stdout = output
	if err := cmd.Run(); err != nil {
		if ctx.Err() != nil {
			return nil, output.truncated, fmt.Errorf("command timed out")
		}
		return nil, output.truncated, err
	}
	return output.data, output.truncated, nil
}

func renderUntrackedGitPatch(dir, path string, limit int) (string, bool, bool) {
	root, rel, err := openProjectPath(dir, path)
	if err != nil {
		return "", false, false
	}
	defer root.Close()
	info, err := root.Stat(rel)
	if err != nil || !info.Mode().IsRegular() {
		return "", false, false
	}
	f, err := root.Open(rel)
	if err != nil {
		return "", false, false
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, int64(limit)+1))
	if err != nil {
		return "", false, false
	}
	truncated := len(data) > limit || info.Size() > int64(limit)
	if len(data) > limit {
		data = data[:limit]
	}
	if !utf8.Valid(data) || bytes.IndexByte(data, 0) >= 0 {
		return fmt.Sprintf("diff --git %s %s\nnew file mode 100644\nBinary files /dev/null and %s differ",
			reviewPatchPath("a/", path), reviewPatchPath("b/", path), reviewPatchPath("b/", path)), true, truncated
	}
	text := string(data)
	lineCount := strings.Count(text, "\n")
	if text != "" && !strings.HasSuffix(text, "\n") {
		lineCount++
	}
	var patch strings.Builder
	fmt.Fprintf(&patch, "diff --git %s %s\nnew file mode 100644\n--- /dev/null\n+++ %s\n@@ -0,0 +1,%d @@\n",
		reviewPatchPath("a/", path), reviewPatchPath("b/", path), reviewPatchPath("b/", path), lineCount)
	if text != "" {
		for _, line := range strings.Split(strings.TrimSuffix(text, "\n"), "\n") {
			patch.WriteByte('+')
			patch.WriteString(line)
			patch.WriteByte('\n')
		}
	}
	if text != "" && !strings.HasSuffix(text, "\n") {
		patch.WriteString("\\ No newline at end of file\n")
	}
	if truncated {
		patch.WriteString("[preview truncated]\n")
	}
	return strings.TrimRight(patch.String(), "\n"), false, truncated
}

func reviewPatchPath(prefix, path string) string {
	value := prefix + filepath.ToSlash(path)
	if strings.ContainsAny(value, " \t\r\n\\\"") {
		return strconv.Quote(value)
	}
	return value
}

func countReviewPatchLines(patch string) (insertions, deletions int) {
	for _, line := range strings.Split(patch, "\n") {
		switch {
		case strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++"):
			insertions++
		case strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---"):
			deletions++
		}
	}
	return insertions, deletions
}

func truncateGitReviewPatch(patch string, limit int) string {
	if limit <= 0 {
		return ""
	}
	const marker = "\n[preview truncated]"
	if limit <= len(marker) {
		return marker[len(marker)-limit:]
	}
	end := limit - len(marker)
	if end > len(patch) {
		end = len(patch)
	}
	for end > 0 && !utf8.ValidString(patch[:end]) {
		end--
	}
	return strings.TrimRight(patch[:end], "\n") + marker
}

// GetProjectGitContext gathers a snapshot of the project's git state for
// the welcome screen. Caps lists at 20 changed / 20 untracked / 5 commits
// so a noisy repo doesn't bloat the response. Each git invocation has a
// 3-second timeout so a hung git operation can't block the UI.
//
// All errors are intentionally swallowed — this is a "show what you can"
// API. The frontend reads IsRepo to decide whether to render the git
// section at all.
func (s *Studio) GetProjectGitContext(projectID string) (*ProjectGitContext, error) {
	s.mu.RLock()
	p, ok := s.projects[projectID]
	s.mu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("project not found: %s", projectID)
	}
	p.mu.RLock()
	dir := p.Directory
	p.mu.RUnlock()
	return gitContextAt(dir), nil
}

// GetSessionGitContext reports the branch and changes from the same checkout
// used by the selected conversation.
func (s *Studio) GetSessionGitContext(projectID, sessionID string) (*ProjectGitContext, error) {
	p, session, err := s.projectSession(projectID, sessionID)
	if err != nil {
		return nil, err
	}
	dir, err := sessionWorkingDirectory(p, session)
	if err != nil {
		return nil, err
	}
	return gitContextAt(dir), nil
}

func gitContextAt(dir string) *ProjectGitContext {
	out := &ProjectGitContext{}

	// rev-parse --is-inside-work-tree confirms we're actually in a git
	// repo (covers both ".git/" and submodules / worktrees).
	if !runGitBool(dir, "rev-parse", "--is-inside-work-tree") {
		return out // not a repo; IsRepo stays false
	}
	out.IsRepo = true

	if branch := runGit(dir, "rev-parse", "--abbrev-ref", "HEAD"); branch != "" {
		out.Branch = branch
	}

	// `git status --porcelain=v1` is stable + script-friendly.
	if status := runGit(dir, "status", "--porcelain=v1"); status != "" {
		const maxChanged = 20
		const maxUntracked = 20
		for _, line := range strings.Split(status, "\n") {
			if len(line) < 4 {
				continue
			}
			code := line[:2]
			path := strings.TrimSpace(line[3:])
			if path == "" {
				continue
			}
			switch {
			case code == "??":
				if len(out.UntrackedFiles) < maxUntracked {
					out.UntrackedFiles = append(out.UntrackedFiles, GitFileChange{Path: path, Status: "untracked"})
				}
			case strings.Contains(code, "M"):
				if len(out.ChangedFiles) < maxChanged {
					out.ChangedFiles = append(out.ChangedFiles, GitFileChange{Path: path, Status: "modified"})
				}
			case strings.Contains(code, "A"):
				if len(out.ChangedFiles) < maxChanged {
					out.ChangedFiles = append(out.ChangedFiles, GitFileChange{Path: path, Status: "added"})
				}
			case strings.Contains(code, "D"):
				if len(out.ChangedFiles) < maxChanged {
					out.ChangedFiles = append(out.ChangedFiles, GitFileChange{Path: path, Status: "deleted"})
				}
			case strings.Contains(code, "R"):
				if len(out.ChangedFiles) < maxChanged {
					out.ChangedFiles = append(out.ChangedFiles, GitFileChange{Path: path, Status: "renamed"})
				}
			default:
				if len(out.ChangedFiles) < maxChanged {
					out.ChangedFiles = append(out.ChangedFiles, GitFileChange{Path: path, Status: "changed"})
				}
			}
		}
	}

	// Recent commits — short hash, subject, and age in seconds since epoch.
	// Use a printable delimiter unlikely to appear in commit messages but
	// that survives the exec pipe (NUL bytes get mangled). `|||~~~|||` is
	// the chosen marker; if a future commit message contains exactly that
	// substring the parse will under-count fields and the line will be
	// dropped — acceptable because the alternative is rendering nothing.
	const sep = "|||~~~|||"
	logFmt := "%h" + sep + "%ct" + sep + "%s"
	if logOut := runGit(dir, "log", "--pretty=format:"+logFmt, "-5"); logOut != "" {
		now := time.Now()
		for _, line := range strings.Split(logOut, "\n") {
			parts := strings.SplitN(line, sep, 3)
			if len(parts) != 3 {
				continue
			}
			hash := parts[0]
			// `%ct` is unix seconds.
			var unix int64
			fmt.Sscanf(parts[1], "%d", &unix)
			ageMs := int64(0)
			ageStr := ""
			if unix > 0 {
				commitTime := time.Unix(unix, 0)
				ageMs = now.Sub(commitTime).Milliseconds()
				ageStr = humanAge(now.Sub(commitTime))
			}
			out.RecentCommits = append(out.RecentCommits, GitCommit{
				Hash:    hash,
				Subject: strings.TrimSpace(parts[2]),
				Age:     ageStr,
				AgeMs:   ageMs,
			})
		}
	}

	// Ahead/behind upstream — "@{u}" syntax fails silently when there's
	// no upstream tracking branch; we just leave AheadBehind empty.
	if ab := runGit(dir, "rev-list", "--left-right", "--count", "HEAD...@{u}"); ab != "" {
		// Output is "<ahead>\t<behind>".
		fields := strings.Fields(ab)
		if len(fields) == 2 {
			ahead, behind := fields[0], fields[1]
			if ahead != "0" || behind != "0" {
				out.AheadBehind = "+" + ahead + " -" + behind
			}
		}
	}

	// Line-count diff stat for uncommitted tracked changes vs HEAD. Each
	// numstat line is "<added>\t<deleted>\t<path>"; binary files show "-".
	// On a repo with no commits yet, `git diff HEAD` fails → empty → skipped.
	if ns := runGit(dir, "diff", "HEAD", "--numstat"); ns != "" {
		for _, line := range strings.Split(ns, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 2 {
				continue
			}
			if a, err := strconv.Atoi(fields[0]); err == nil {
				out.Insertions += a
			}
			if d, err := strconv.Atoi(fields[1]); err == nil {
				out.Deletions += d
			}
		}
	}
	return out
}

// runGit executes `git <args>` in dir with a 3-second timeout, returning
// stdout trimmed. Any error or non-zero exit yields "". The command is run
// synchronously under CommandContext: this guarantees that the child is reaped
// before return and avoids the former timeout race where a detached goroutine
// kept writing out/err after its caller had returned. Output remains bounded
// even for huge repositories or pathological Git filters.
func runGit(dir string, args ...string) string {
	return runGitWithTimeout(dir, gitReadTimeout, args...)
}

func runGitWithTimeout(dir string, timeout time.Duration, args ...string) string {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	full := append([]string{"-C", dir}, args...)
	cmd := exec.CommandContext(ctx, "git", full...)
	cmd.WaitDelay = gitWaitDelay
	output := &cappedCommandOutput{limit: maxGitOutputBytes}
	cmd.Stdout = output
	if err := cmd.Run(); err != nil {
		return ""
	}
	return strings.TrimRight(output.String(), "\n")
}

// runGitBool returns true iff `git <args>` exits 0 and prints "true".
// Used for boolean queries like rev-parse --is-inside-work-tree.
func runGitBool(dir string, args ...string) bool {
	return runGit(dir, args...) == "true"
}

// humanAge converts a duration into a short relative string like
// "3 minutes ago", "2 days ago", "5 weeks ago". Used for the recent-
// commits list in the welcome screen.
func humanAge(d time.Duration) string {
	if d < time.Minute {
		return "just now"
	}
	if d < time.Hour {
		mins := int(d.Minutes())
		return plural(mins, "minute") + " ago"
	}
	if d < 24*time.Hour {
		hours := int(d.Hours())
		return plural(hours, "hour") + " ago"
	}
	days := int(d.Hours() / 24)
	if days < 7 {
		return plural(days, "day") + " ago"
	}
	if days < 30 {
		weeks := days / 7
		return plural(weeks, "week") + " ago"
	}
	if days < 365 {
		months := days / 30
		return plural(months, "month") + " ago"
	}
	years := days / 365
	return plural(years, "year") + " ago"
}

func plural(n int, unit string) string {
	if n == 1 {
		return "1 " + unit
	}
	return fmt.Sprintf("%d %ss", n, unit)
}
